In [83]:
import numpy as np
from scipy.linalg import solve, det, inv

Zadanie 4

In [84]:
def join_vectors(A, b):
    B = A
    for i in range(len(A)):
        B[i].append(b[i])
    return B

In [85]:
def Gauss_elimination_matrix(M): 
    for k in range(len(M) - 1):                 #kolumny
        biggest_num = 0
        for i in range(k, len(M)):              #wiersze
            if M[i][k] != 0 and abs(M[i][k]) > abs(biggest_num):
                biggest_num = M[i][k]
                biggest_num_index = i

        x = M[k]
        M[k] = M[biggest_num_index]
        M[biggest_num_index] = x
    
        print(M)
        for i in range(k+1, len(M)):
            a = M[i][k]/M[k][k]
            for j in range(len(M[0])):
                M[i][j] -= a * M[k][j]
        print(M)
        print('-----------------------')
    return M

W = [[0, 2, 2, 1], [3, 3, 0, 3], [1, 0, 1, 2]]
print(Gauss_elimination_matrix(W))

[[3, 3, 0, 3], [0, 2, 2, 1], [1, 0, 1, 2]]
[[3, 3, 0, 3], [0.0, 2.0, 2.0, 1.0], [0.0, -1.0, 1.0, 1.0]]
-----------------------
[[3, 3, 0, 3], [0.0, 2.0, 2.0, 1.0], [0.0, -1.0, 1.0, 1.0]]
[[3, 3, 0, 3], [0.0, 2.0, 2.0, 1.0], [0.0, 0.0, 2.0, 1.5]]
-----------------------
[[3, 3, 0, 3], [0.0, 2.0, 2.0, 1.0], [0.0, 0.0, 2.0, 1.5]]


In [86]:
def Gauss_elimination_answers(M):

    M = M[::-1]
    X = []

    for i in range(len(M)):
        x = (M[i][-1] - sum(X[::-1][j]*M[i][-1-i:-1][j] for j in range(len(X)))) / (M[i][-2 - i])
        X.append(x)

    return X[::-1]

In [87]:
A = [[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]
b = [1, 1, -4, -2, -1]

In [88]:
def Gauss_elimination(A, b):
    M = join_vectors(A, b)
    return Gauss_elimination_answers(Gauss_elimination_matrix(M))

print(Gauss_elimination(A, b))

[[1, 2, 0, -2, 0, -4], [0, 1, 0, 2, -1, 1], [0, 0, 2, 1, 2, 1], [0, 0, 0, -1, 1, -2], [0, 1, -1, 1, -1, -1]]
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0.0, 2.0, -1.0, 1.0], [0.0, 0.0, 2.0, 1.0, 2.0, 1.0], [0.0, 0.0, 0.0, -1.0, 1.0, -2.0], [0.0, 1.0, -1.0, 1.0, -1.0, -1.0]]
-----------------------
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0.0, 2.0, -1.0, 1.0], [0.0, 0.0, 2.0, 1.0, 2.0, 1.0], [0.0, 0.0, 0.0, -1.0, 1.0, -2.0], [0.0, 1.0, -1.0, 1.0, -1.0, -1.0]]
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0.0, 2.0, -1.0, 1.0], [0.0, 0.0, 2.0, 1.0, 2.0, 1.0], [0.0, 0.0, 0.0, -1.0, 1.0, -2.0], [0.0, 0.0, -1.0, -1.0, 0.0, -2.0]]
-----------------------
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0.0, 2.0, -1.0, 1.0], [0.0, 0.0, 2.0, 1.0, 2.0, 1.0], [0.0, 0.0, 0.0, -1.0, 1.0, -2.0], [0.0, 0.0, -1.0, -1.0, 0.0, -2.0]]
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0.0, 2.0, -1.0, 1.0], [0.0, 0.0, 2.0, 1.0, 2.0, 1.0], [0.0, 0.0, 0.0, -1.0, 1.0, -2.0], [0.0, 0.0, 0.0, -0.5, 1.0, -1.5]]
-----------------------
[[1, 2, 0, -2, 0, -4], [0.0, 1.0, 0

In [89]:
A = [[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]
b = [1, 1, -4, -2, -1]

In [90]:
x = solve(np.array(A) ,np.array(b))
print(x)

[ 2. -2.  1.  1. -1.]


Zadanie 5

In [91]:
points = [[0,-1], [1,1], [3,3], [5,2], [6,-2]]
Y = []
X = []
for point in points:
    Y.append(point[1])
    X.append([point[0]**0, point[0]**1, point[0]**2, point[0]**3, point[0]**4])

print(Gauss_elimination(X, Y))

[[1, 0, 0, 0, 0, -1], [1, 1, 1, 1, 1, 1], [1, 3, 9, 27, 81, 3], [1, 5, 25, 125, 625, 2], [1, 6, 36, 216, 1296, -2]]
[[1, 0, 0, 0, 0, -1], [0.0, 1.0, 1.0, 1.0, 1.0, 2.0], [0.0, 3.0, 9.0, 27.0, 81.0, 4.0], [0.0, 5.0, 25.0, 125.0, 625.0, 3.0], [0.0, 6.0, 36.0, 216.0, 1296.0, -1.0]]
-----------------------
[[1, 0, 0, 0, 0, -1], [0.0, 6.0, 36.0, 216.0, 1296.0, -1.0], [0.0, 3.0, 9.0, 27.0, 81.0, 4.0], [0.0, 5.0, 25.0, 125.0, 625.0, 3.0], [0.0, 1.0, 1.0, 1.0, 1.0, 2.0]]
[[1, 0, 0, 0, 0, -1], [0.0, 6.0, 36.0, 216.0, 1296.0, -1.0], [0.0, 0.0, -9.0, -81.0, -567.0, 4.5], [0.0, 0.0, -5.0, -55.0, -455.0, 3.8333333333333335], [0.0, 0.0, -5.0, -35.0, -215.0, 2.1666666666666665]]
-----------------------
[[1, 0, 0, 0, 0, -1], [0.0, 6.0, 36.0, 216.0, 1296.0, -1.0], [0.0, 0.0, -9.0, -81.0, -567.0, 4.5], [0.0, 0.0, -5.0, -55.0, -455.0, 3.8333333333333335], [0.0, 0.0, -5.0, -35.0, -215.0, 2.1666666666666665]]
[[1, 0, 0, 0, 0, -1], [0.0, 6.0, 36.0, 216.0, 1296.0, -1.0], [0.0, 0.0, -9.0, -81.0, -567.0, 4.5],

In [92]:
Y = []
X = []
for point in points:
    Y.append(point[1])
    X.append([point[0]**0, point[0]**1, point[0]**2, point[0]**3, point[0]**4])

print(solve(np.array(X), np.array(Y)))

[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


Zadanie 6

In [93]:
A = [[3.5, 2.77, -0.76, 1.8], [-1.8, 2.68, 3.44, -0.09], [0.27, 5.07, 6.9, 1.61], [1.71, 5.45, 2.68, 1.71]]
b = [7.31, 4.23, 13.85, 11.55]
X = Gauss_elimination(A, b)
print(X)
A = [[3.5, 2.77, -0.76, 1.8], [-1.8, 2.68, 3.44, -0.09], [0.27, 5.07, 6.9, 1.61], [1.71, 5.45, 2.68, 1.71]]
print(np.array(A) @ np.array(X))

[[3.5, 2.77, -0.76, 1.8, 7.31], [-1.8, 2.68, 3.44, -0.09, 4.23], [0.27, 5.07, 6.9, 1.61, 13.85], [1.71, 5.45, 2.68, 1.71, 11.55]]
[[3.5, 2.77, -0.76, 1.8, 7.31], [2.220446049250313e-16, 4.104571428571429, 3.049142857142857, 0.8357142857142859, 7.989428571428572], [0.0, 4.856314285714286, 6.958628571428572, 1.4711428571428573, 13.286085714285713], [0.0, 4.096657142857143, 3.0513142857142856, 0.8305714285714285, 7.978542857142858]]
-----------------------
[[3.5, 2.77, -0.76, 1.8, 7.31], [0.0, 4.856314285714286, 6.958628571428572, 1.4711428571428573, 13.286085714285713], [2.220446049250313e-16, 4.104571428571429, 3.049142857142857, 0.8357142857142859, 7.989428571428572], [0.0, 4.096657142857143, 3.0513142857142856, 0.8305714285714285, 7.978542857142858]]
[[3.5, 2.77, -0.76, 1.8, 7.31], [0.0, 4.856314285714286, 6.958628571428572, 1.4711428571428573, 13.286085714285713], [2.220446049250313e-16, 0.0, -2.8323109236281496, -0.4077000782486424, -3.2400110018767894], [0.0, 0.0, -2.81879908925640

In [94]:
A = [[3.5, 2.77, -0.76, 1.8], [-1.8, 2.68, 3.44, -0.09], [0.27, 5.07, 6.9, 1.61], [1.71, 5.45, 2.68, 1.71]]
b = [7.31, 4.23, 13.85, 11.55]
X = solve(np.array(A), np.array(b))
print(X)
print(det(np.array(A)))
print(np.array(A) @ X)

[1. 1. 1. 1.]
-0.22579733999999005
[ 7.31  4.23 13.85 11.55]


In [95]:
E = np.array([1.0000000000000442, 1.0000000000000102, 1.0000000000000129, 0.9999999999999036])
F = np.array([1.0, 1.0, 1.0, 1.0])
e = sum((F - E)**2) / 4
print(e)

2.8773331739387083e-27


Zadanie 7

In [96]:
A = [[10, -2, -1, 2, 3, 1, -4, 7], [5, 11, 3, 10, -3, 3, 3, -4], [7, 12, 1, 5, 3, -12, 2, 3], [8, 7, -2, 1, 3, 2, 2, 4], [2, -15, -1, 1, 4, -1, 8, 3], [4, 2, 9, 1, 12, -1, 4, 1], [-1, 4, -7, -1, 1, 1, -1, -3], [-1, 3, 4, 1, 3, -4, 7, 6]]
b = [0, 12, -5, 3, -25, -26, 9, -7]

X = Gauss_elimination(A, b)
print(X)

[[10, -2, -1, 2, 3, 1, -4, 7, 0], [5, 11, 3, 10, -3, 3, 3, -4, 12], [7, 12, 1, 5, 3, -12, 2, 3, -5], [8, 7, -2, 1, 3, 2, 2, 4, 3], [2, -15, -1, 1, 4, -1, 8, 3, -25], [4, 2, 9, 1, 12, -1, 4, 1, -26], [-1, 4, -7, -1, 1, 1, -1, -3, 9], [-1, 3, 4, 1, 3, -4, 7, 6, -7]]
[[10, -2, -1, 2, 3, 1, -4, 7, 0], [0.0, 12.0, 3.5, 9.0, -4.5, 2.5, 5.0, -7.5, 12.0], [0.0, 13.4, 1.7, 3.6, 0.9000000000000004, -12.7, 4.8, -1.8999999999999995, -5.0], [0.0, 8.6, -1.2, -0.6000000000000001, 0.5999999999999996, 1.2, 5.2, -1.6000000000000005, 3.0], [0.0, -14.6, -0.8, 0.6, 3.4, -1.2, 8.8, 1.5999999999999999, -25.0], [0.0, 2.8, 9.4, 0.19999999999999996, 10.8, -1.4, 5.6, -1.8000000000000003, -26.0], [0.0, 3.8, -7.1, -0.8, 1.3, 1.1, -1.4, -2.3, 9.0], [0.0, 2.8, 3.9, 1.2, 3.3, -3.9, 6.6, 6.7, -7.0]]
-----------------------
[[10, -2, -1, 2, 3, 1, -4, 7, 0], [0.0, -14.6, -0.8, 0.6, 3.4, -1.2, 8.8, 1.5999999999999999, -25.0], [0.0, 13.4, 1.7, 3.6, 0.9000000000000004, -12.7, 4.8, -1.8999999999999995, -5.0], [0.0, 8.6, -1.

In [97]:
A = [[10, -2, -1, 2, 3, 1, -4, 7], [5, 11, 3, 10, -3, 3, 3, -4], [7, 12, 1, 5, 3, -12, 2, 3], [8, 7, -2, 1, 3, 2, 2, 4], [2, -15, -1, 1, 4, -1, 8, 3], [4, 2, 9, 1, 12, -1, 4, 1], [-1, 4, -7, -1, 1, 1, -1, -3], [-1, 3, 4, 1, 3, -4, 7, 6]]
b = [0, 12, -5, 3, -25, -26, 9, -7]

X = solve(np.array(A), np.array(b))
print(X)

[-1.  1. -1.  1. -1.  1. -1.  1.]


Zadanie 8

In [98]:
A = np.array([[2, -1, 0, 0, 0, 0], [-1, 2, -1, 0, 0, 0], [0, -1, 2, -1, 0, 0], [0, 0, -1, 2, -1, 0], [0, 0, 0, -1, 2, -1], [0, 0, 0, 0, -1, 5]])
inversed_A = inv(A)
print(inversed_A)
#nie jest trójdiagonalna
#jest symetryczna względem diagonali

[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


Zadanie 9

In [99]:
B = np.array([[1, 3, -9, 6, 4], [2, -1, 6, 7, 1], [3, 2, -3, 15, 5], [8, 1, 1, 4, 2], [11, 1, -2, 18, 7]])
inversed_B = inv(B)
print(inversed_B)
print(B @ inversed_B)

[[-0.28947368 -0.34210526  0.18421053  0.10526316  0.05263158]
 [ 0.25        0.25        0.25        0.5        -0.5       ]
 [ 0.41746411  0.58014354 -0.31937799  0.08373206 -0.11722488]
 [-0.5        -0.5         0.5         0.          0.        ]
 [ 1.82416268  1.95334928 -1.70215311 -0.21291866  0.09808612]]
[[ 1.00000000e+00 -2.66453526e-15  1.77635684e-15  0.00000000e+00
  -1.11022302e-16]
 [ 8.88178420e-16  1.00000000e+00 -8.88178420e-16 -5.55111512e-17
  -1.38777878e-16]
 [-1.77635684e-15  0.00000000e+00  1.00000000e+00 -2.22044605e-16
  -2.22044605e-16]
 [-4.44089210e-16 -8.88178420e-16  8.88178420e-16  1.00000000e+00
  -2.22044605e-16]
 [-1.77635684e-15  0.00000000e+00  1.77635684e-15 -2.22044605e-16
   1.00000000e+00]]
